;; ((nil . ((fill-column . 80)))
;;  (org-mode . ((mode . auto-fill)
;;               (org-hugo-base-dir . "../.")
;;               (org-hugo-footer . "\n\nThis text is auto inserted at the end of the exported Markdown.")
;;               (org-hugo-export-with-toc . t)
;;               (org-hugo-export-with-section-numbers . t)
;;               (org-hugo-export-creator-string . "Guangda Zhang")
;;               (org-hugo-date-format . "%Y-%m-%d")
;;               (eval . (org-hugo-auto-export-mode)))))
(("content-org/"
  . ((org-mode . ((mode . auto-fill)
                  (org-hugo-base-dir . "./")
                  ;; (org-hugo-footer . "\n\nThis text is auto inserted at the end of the exported Markdown.")
                  ;; (org-hugo-export-with-toc . t)
                  ;; (org-hugo-export-with-section-numbers . t)
                  ;; (org-hugo-export-creator-string . "Guangda Zhang")
                  ;; (org-hugo-date-format . "%Y-%m-%d")
                  (eval . (org-hugo-auto-export-mode)))))))
